import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { migrate } from "drizzle-orm/node-postgres/migrator";

import type { DatabaseConnection } from "./client.js";

/**
 * Folder with the SQL migrations generated by drizzle-kit: `MIGRATIONS_DIR`
 * if set, else `drizzle/` next to a bundle, else the folder of this package.
 */
export function migrationsFolder(): string {
  const configured = process.env["MIGRATIONS_DIR"];
  if (configured) return configured;
  const here = dirname(fileURLToPath(import.meta.url));
  // A bundle (CLI, API image) ships the migrations next to itself.
  const bundled = resolve(here, "drizzle");
  if (existsSync(resolve(bundled, "meta/_journal.json"))) return bundled;
  return resolve(here, "../drizzle");
}

/** Applies all pending migrations. Used by the CLI and the e2e setup. */
export async function migrateDatabase(
  connection: Pick<DatabaseConnection, "db">,
): Promise<void> {
  // The node-postgres migrator accepts any database of that driver.
  await migrate(connection.db as Parameters<typeof migrate>[0], {
    migrationsFolder: migrationsFolder(),
  });
}
